### ISSUE TITLE
Mongodb on APK

### ISSUE THREAD

**Issue by ihmc3jn09hk** [DannyBen/docker-alpine-mongo#1]
Hi Danny,

   Where did you get the mongodb package from? I am using Alpine 3.11.3. I could not find the package in the apk:

``
$apk search -a mongodb
``
and it returns
``
mongodb-tools-4.2.1-r0
``

Did you compile it from source?

**Comment by DannyBen** [comment]
No, I did not compile anything.

It was in the apk repository until Alpine 3.9 as it seems.
From the little I can find, it seems like MongoDB changed their licensing, and are therefore being removed from package repositories....

See [here for example](https://www.reddit.com/r/archlinux/comments/ahkw72/mongodb_is_removed_from_repos_anyone_know_why/)

If you find some information to shed light on this, please share. I will do the same.

**Comment by ihmc3jn09hk** [comment]
> No, I did not compile anything.
> 
> It was in the apk repository until Alpine 3.9 as it seems.
> From the little I can find, it seems like MongoDB changed their licensing, and are therefore being removed from package repositories....
> 
> See [here for example].(https://www.reddit.com/r/archlinux/comments/ahkw72/mongodb_is_removed_from_repos_anyone_know_why/)
> 
> If you find some information to shed light on this, please share. I will do the same.

Ooo. How sad for the move made by MongoDB. Gonna find an alternative.
Much thx

**Comment by DannyBen** [comment]
> Ooo. How sad for the move made by MongoDB. Gonna find an alternative.

Agree...
